name: analysis
dependencies:
  - python=3.9.7
  - cvxopt
  - pandas==1.3.4
  - numpy==1.20.3
  - matplotlib==3.4.3
  - scikit-learn==1.0.2
  - yellowbrick==1.4
  - seaborn==0.11.2
  - ipykernel
  - pip
  - pip:
    - pm4py==2.2.19.1