channels: 
  - conda-forge
dependencies:
  - python=3.9.7
  - pandas==1.3.4
  - numpy==1.20.3
  - matplotlib==3.4.3
  - scikit-learn==1.0.2
  - seaborn==0.11.2
  - ipykernel
  - jupyter
  - pip
  - pip:
    - yellowbrick==1.4
    - pm4py==2.2.19.1